name = "job-board-api-widget-v1"
main = "src/index.js"
node_compat = true
compatibility_date = "2022-10-06"
send_metrics = true

[build]
command="npm run handlebars"
watch_dir="views/"

[env.pr]
name = "job-board-api-widget-pr"
vars = { ENVIRONMENT = "pr" }

[env.test]
name = "job-board-api-widget-test"
vars = { ENVIRONMENT = "test" }
route = "test.api.jobs.tampa.dev/*"

[env.staging]
name = "job-board-api-widget-staging"
vars = { ENVIRONMENT = "staging" }
route = "staging.api.jobs.tampa.dev/*"

[env.production]
name = "job-board-api-widget-prod"
vars = { ENVIRONMENT = "production" }
routes = [
  "api.jobs.tampa.dev/*",
  "api.jobs.tampa.dev/v1/widget"
]
