name: "Build Pull Request"

on:
  workflow_dispatch:
    paths-ignore: 
      - '.**'
      - 'LICENSE'
      - 'ACKNOWLEDGEMENTS'
      - '**.md'
  pull_request:
    paths-ignore: # do not build for game-irrelvant changes
      - '.**'
      - 'LICENSE'
      - 'ACKNOWLEDGEMENTS'
      - '**.md'

jobs:
  build:
    name: "Build PR"
    if: ${{ (github.event.action == 'synchronize' && github.event.label.name != 'skip preview') || github.event.action != 'synchronize' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: current
        cache: 'npm'
    - run: npm ci
    - name: Run test
      uses: cloudflare/wrangler-action@2.0.0
      with:
        apiToken: 'dummy-key-that-should-make-the-action-run-lol'
        command: publish --env pr --dry-run --outdir ./out
